
function _localRecord(){
  this._record=[0,0,0]
  this._pct = ".000"
  this._pf=0
  this._pa=0
  this._diff=0
  this._strk="--"
}

function _overallRecord(){
  this._overall=[0,0,0]
  this._pct = ".000"
  this._div=new _localRecord()
  this._conf=new _localRecord()
  this._home=new _localRecord()
  this._road=new _localRecord()
  this._pf=0
  this._pa=0
  this._diff=0
  this._strk="--"
}

var SHOW_TEAMS = [

  [ // NFL
    { _ico:"ne.png",_team:"New England Patriots",_conf:"AFC",_div:"AFC EAST",_bye:0,_record:new _overallRecord() },
    { _ico:"nyj.png",_team:"New York Jets",_conf:"AFC",_div:"AFC EAST",_bye:0,_record:new _overallRecord() },
    { _ico:"buf.png",_team:"Buffalo Bills",_conf:"AFC",_div:"AFC EAST",_bye:0,_record:new _overallRecord() },
    { _ico:"mia.png",_team:"Miami Dolphins",_conf:"AFC",_div:"AFC EAST",_bye:0,_record:new _overallRecord() },
    { _ico:"den.png",_team:"Denver Broncos",_conf:"AFC",_div:"AFC WEST",_bye:0,_record:new _overallRecord() },
    { _ico:"sd.png",_team:"San Diego Chargers",_conf:"AFC",_div:"AFC WEST",_bye:0,_record:new _overallRecord() },
    { _ico:"kc.png",_team:"Kansas City Chiefs",_conf:"AFC",_div:"AFC WEST",_bye:0,_record:new _overallRecord() },
    { _ico:"oak.png",_team:"Oakland Raiders",_conf:"AFC",_div:"AFC WEST",_bye:0,_record:new _overallRecord() },
    { _ico:"cin.png",_team:"Cincinnati Bengals",_conf:"AFC",_div:"AFC NORTH",_bye:0,_record:new _overallRecord() },
    { _ico:"cle.png",_team:"Cleveland Browns",_conf:"AFC",_div:"AFC NORTH",_bye:0,_record:new _overallRecord() },
    { _ico:"bal.png",_team:"Baltimore Ravens",_conf:"AFC",_div:"AFC NORTH",_bye:0,_record:new _overallRecord() },
    { _ico:"pit.png",_team:"Pittsburgh Steelers",_conf:"AFC",_div:"AFC NORTH",_bye:0,_record:new _overallRecord() },
    { _ico:"ten.png",_team:"Tennessee Titans",_conf:"AFC",_div:"AFC SOUTH",_bye:0,_record:new _overallRecord() },
    { _ico:"ind.png",_team:"Indianapolis Colts",_conf:"AFC",_div:"AFC SOUTH",_bye:0,_record:new _overallRecord() },
    { _ico:"hou.png",_team:"Houston Texans",_conf:"AFC",_div:"AFC SOUTH",_bye:0,_record:new _overallRecord() },
    { _ico:"jax.png",_team:"Jacksonville Jaguars",_conf:"AFC",_div:"AFC SOUTH",_bye:0,_record:new _overallRecord() },
    { _ico:"phi.png",_team:"Philadelphia Eagles",_conf:"NFC",_div:"NFC EAST",_bye:0,_record:new _overallRecord() },
    { _ico:"was.png",_team:"Washington Redskins",_conf:"NFC",_div:"NFC EAST",_bye:0,_record:new _overallRecord() },
    { _ico:"nyg.png",_team:"New York Giants",_conf:"NFC",_div:"NFC EAST",_bye:0,_record:new _overallRecord() },
    { _ico:"dal.png",_team:"Dallas Cowboys",_conf:"NFC",_div:"NFC EAST",_bye:0,_record:new _overallRecord() },
    { _ico:"la.png",_team:"Los Angeles Rams",_conf:"NFC",_div:"NFC WEST",_bye:0,_record:new _overallRecord() },
    { _ico:"sea.png",_team:"Seattle Seahawks",_conf:"NFC",_div:"NFC WEST",_bye:0,_record:new _overallRecord() },
    { _ico:"ari.png",_team:"Arizona Cardinals",_conf:"NFC",_div:"NFC WEST",_bye:0,_record:new _overallRecord() },
    { _ico:"sf.png",_team:"San Francisco 49ers",_conf:"NFC",_div:"NFC WEST",_bye:0,_record:new _overallRecord() },
    { _ico:"det.png",_team:"Detroit Lions",_conf:"NFC",_div:"NFC NORTH",_bye:0,_record:new _overallRecord() },
    { _ico:"chi.png",_team:"Chicago Bears",_conf:"NFC",_div:"NFC NORTH",_bye:0,_record:new _overallRecord() },
    { _ico:"gb.png",_team:"Green Bay Packers",_conf:"NFC",_div:"NFC NORTH",_bye:0,_record:new _overallRecord() },
    { _ico:"min.png",_team:"Minnesota Vikings",_conf:"NFC",_div:"NFC NORTH",_bye:0,_record:new _overallRecord() },
    { _ico:"car.png",_team:"Carolina Panthers",_conf:"NFC",_div:"NFC SOUTH",_bye:0,_record:new _overallRecord() },
    { _ico:"no.png",_team:"New Orleans Saints",_conf:"NFC",_div:"NFC SOUTH",_bye:0,_record:new _overallRecord() },
    { _ico:"tb.png",_team:"Tamp Bay Buccaneers",_conf:"NFC",_div:"NFC SOUTH",_bye:0,_record:new _overallRecord() },
    { _ico:"atl.png",_team:"Atlanta Falcons",_conf:"NFC",_div:"NFC SOUTH",_bye:0,_record:new _overallRecord() },
  ],
  
  [ // NCAA DIV I
    { _ico:"i(33)",_team:"South Florida",_conf:"American Athletic Conference",_div:"American Athletic Conference East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(34)",_team:"UCF",_conf:"American Athletic Conference",_div:"American Athletic Conference East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(35)",_team:"Temple",_conf:"American Athletic Conference",_div:"American Athletic Conference East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(36)",_team:"Connecticut",_conf:"American Athletic Conference",_div:"American Athletic Conference East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(37)",_team:"East Carolina",_conf:"American Athletic Conference",_div:"American Athletic Conference East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(38)",_team:"Cincinnati",_conf:"American Athletic Conference",_div:"American Athletic Conference East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(39)",_team:"Navy",_conf:"American Athletic Conference",_div:"American Athletic Conference West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(40)",_team:"Memphis",_conf:"American Athletic Conference",_div:"American Athletic Conference West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(41)",_team:"Tulsa",_conf:"American Athletic Conference",_div:"American Athletic Conference West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(42)",_team:"Houston",_conf:"American Athletic Conference",_div:"American Athletic Conference West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(43)",_team:"Tulane",_conf:"American Athletic Conference",_div:"American Athletic Conference West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(44)",_team:"SMU",_conf:"American Athletic Conference",_div:"American Athletic Conference West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(45)",_team:"Clemson",_conf:"Atlantic Coast Conference (ACC)",_div:"Atlantic",_bye:0,_record:new _overallRecord() },
    { _ico:"i(46)",_team:"NC State",_conf:"Atlantic Coast Conference (ACC)",_div:"Atlantic",_bye:0,_record:new _overallRecord() },
    { _ico:"i(47)",_team:"Louisville",_conf:"Atlantic Coast Conference (ACC)",_div:"Atlantic",_bye:0,_record:new _overallRecord() },
    { _ico:"i(48)",_team:"Wake Forest",_conf:"Atlantic Coast Conference (ACC)",_div:"Atlantic",_bye:0,_record:new _overallRecord() },
    { _ico:"i(49)",_team:"Florida State",_conf:"Atlantic Coast Conference (ACC)",_div:"Atlantic",_bye:0,_record:new _overallRecord() },
    { _ico:"i(50)",_team:"Syracuse",_conf:"Atlantic Coast Conference (ACC)",_div:"Atlantic",_bye:0,_record:new _overallRecord() },
    { _ico:"i(51)",_team:"Boston College",_conf:"Atlantic Coast Conference (ACC)",_div:"Atlantic",_bye:0,_record:new _overallRecord() },
    { _ico:"i(52)",_team:"Virginia Tech",_conf:"Atlantic Coast Conference (ACC)",_div:"Coastal",_bye:0,_record:new _overallRecord() },
    { _ico:"i(53)",_team:"Virginia",_conf:"Atlantic Coast Conference (ACC)",_div:"Coastal",_bye:0,_record:new _overallRecord() },
    { _ico:"i(54)",_team:"North Carolina",_conf:"Atlantic Coast Conference (ACC)",_div:"Coastal",_bye:0,_record:new _overallRecord() },
    { _ico:"i(55)",_team:"Miami",_conf:"Atlantic Coast Conference (ACC)",_div:"Coastal",_bye:0,_record:new _overallRecord() },
    { _ico:"i(56)",_team:"Pittsburgh",_conf:"Atlantic Coast Conference (ACC)",_div:"Coastal",_bye:0,_record:new _overallRecord() },
    { _ico:"i(57)",_team:"Georgia Tech",_conf:"Atlantic Coast Conference (ACC)",_div:"Coastal",_bye:0,_record:new _overallRecord() },
    { _ico:"i(58)",_team:"Duke",_conf:"Atlantic Coast Conference (ACC)",_div:"Coastal",_bye:0,_record:new _overallRecord() },
    { _ico:"i(59)",_team:"Baylor",_conf:"Big 12 Conference",_div:"Big 12",_bye:0,_record:new _overallRecord() },
    { _ico:"i(60)",_team:"Oklahoma",_conf:"Big 12 Conference",_div:"Big 12",_bye:0,_record:new _overallRecord() },
    { _ico:"i(61)",_team:"West Virginia",_conf:"Big 12 Conference",_div:"Big 12",_bye:0,_record:new _overallRecord() },
    { _ico:"i(62)",_team:"Oklahoma State",_conf:"Big 12 Conference",_div:"Big 12",_bye:0,_record:new _overallRecord() },
    { _ico:"i(63)",_team:"TCU",_conf:"Big 12 Conference",_div:"Big 12",_bye:0,_record:new _overallRecord() },
    { _ico:"i(64)",_team:"Kansas State",_conf:"Big 12 Conference",_div:"Big 12",_bye:0,_record:new _overallRecord() },
    { _ico:"i(65)",_team:"Texas Tech",_conf:"Big 12 Conference",_div:"Big 12",_bye:0,_record:new _overallRecord() },
    { _ico:"i(66)",_team:"Texas",_conf:"Big 12 Conference",_div:"Big 12",_bye:0,_record:new _overallRecord() },
    { _ico:"i(67)",_team:"Kansas",_conf:"Big 12 Conference",_div:"Big 12",_bye:0,_record:new _overallRecord() },
    { _ico:"i(68)",_team:"Iowa State",_conf:"Big 12 Conference",_div:"Big 12",_bye:0,_record:new _overallRecord() },
    { _ico:"i(69)",_team:"Michigan",_conf:"Big Ten Conference",_div:"Big Ten East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(70)",_team:"Ohio State",_conf:"Big Ten Conference",_div:"Big Ten East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(71)",_team:"Penn State",_conf:"Big Ten Conference",_div:"Big Ten East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(72)",_team:"Maryland",_conf:"Big Ten Conference",_div:"Big Ten East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(73)",_team:"Indiana",_conf:"Big Ten Conference",_div:"Big Ten East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(74)",_team:"Michigan State",_conf:"Big Ten Conference",_div:"Big Ten East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(75)",_team:"Rutgers",_conf:"Big Ten Conference",_div:"Big Ten East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(76)",_team:"Nebraska",_conf:"Big Ten Conference",_div:"Big Ten West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(77)",_team:"Iowa",_conf:"Big Ten Conference",_div:"Big Ten West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(78)",_team:"Wisconsin",_conf:"Big Ten Conference",_div:"Big Ten West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(79)",_team:"Purdue",_conf:"Big Ten Conference",_div:"Big Ten West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(80)",_team:"Northwestern",_conf:"Big Ten Conference",_div:"Big Ten West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(81)",_team:"Minnesota",_conf:"Big Ten Conference",_div:"Big Ten West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(82)",_team:"Illinois",_conf:"Big Ten Conference",_div:"Big Ten West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(83)",_team:"Middle Tennessee",_conf:"Conference USA",_div:"East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(84)",_team:"Old Dominion",_conf:"Conference USA",_div:"East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(85)",_team:"Florida Intl",_conf:"Conference USA",_div:"East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(86)",_team:"Western Kentucky",_conf:"Conference USA",_div:"East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(87)",_team:"Charlotte",_conf:"Conference USA",_div:"East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(88)",_team:"Marshall",_conf:"Conference USA",_div:"East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(89)",_team:"Florida Atlantic",_conf:"Conference USA",_div:"East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(90)",_team:"Southern Mississippi",_conf:"Conference USA",_div:"West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(91)",_team:"Louisiana Tech",_conf:"Conference USA",_div:"West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(92)",_team:"North Texas",_conf:"Conference USA",_div:"West",_bye:0,_record:new _overallRecord() },    
    { _ico:"i(93)",_team:"Texas San Antonio",_conf:"Conference USA",_div:"West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(94)",_team:"Texas El-Paso (UTEP)",_conf:"Conference USA",_div:"West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(95)",_team:"Rice",_conf:"Conference USA",_div:"West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(96)",_team:"Brigham Young (BYU)",_conf:"FBS Independants",_div:"Independants",_bye:0,_record:new _overallRecord() },
    { _ico:"i(97)",_team:"Army",_conf:"FBS Independants",_div:"Independants",_bye:0,_record:new _overallRecord() },
    { _ico:"i(98)",_team:"Notre Dame",_conf:"FBS Independants",_div:"Independants",_bye:0,_record:new _overallRecord() },
    { _ico:"i(99)",_team:"Massachusetts",_conf:"FBS Independants",_div:"Independants",_bye:0,_record:new _overallRecord() },
    { _ico:"i(100)",_team:"Akron",_conf:"Mid-American Conference",_div:"Mid-American East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(101)",_team:"Ohio",_conf:"Mid-American Conference",_div:"Mid-American East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(102)",_team:"Kent State",_conf:"Mid-American Conference",_div:"Mid-American East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(103)",_team:"Buffalo",_conf:"Mid-American Conference",_div:"Mid-American East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(104)",_team:"Bowling Green",_conf:"Mid-American Conference",_div:"Mid-American East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(105)",_team:"Miami (Ohio)",_conf:"Mid-American Conference",_div:"Mid-American East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(106)",_team:"Western Michigan",_conf:"Mid-American Conference",_div:"Mid-American West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(107)",_team:"Toledo",_conf:"Mid-American Conference",_div:"Mid-American West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(108)",_team:"Central Michigan",_conf:"Mid-American Conference",_div:"Mid-American West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(109)",_team:"Eastern Michigan",_conf:"Mid-American Conference",_div:"Mid-American West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(110)",_team:"Northern Illinois",_conf:"Mid-American Conference",_div:"Mid-American West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(111)",_team:"Ball State",_conf:"Mid-American Conference",_div:"Mid-American West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(112)",_team:"Boise State",_conf:"Mountain West Conference",_div:"Mountain West - Mountain",_bye:0,_record:new _overallRecord() },
    { _ico:"i(113)",_team:"Wyoming",_conf:"Mountain West Conference",_div:"Mountain West - Mountain",_bye:0,_record:new _overallRecord() },
    { _ico:"i(114)",_team:"Air Force",_conf:"Mountain West Conference",_div:"Mountain West - Mountain",_bye:0,_record:new _overallRecord() },
    { _ico:"i(115)",_team:"Colorado State",_conf:"Mountain West Conference",_div:"Mountain West - Mountain",_bye:0,_record:new _overallRecord() },
    { _ico:"i(116)",_team:"New Mexico",_conf:"Mountain West Conference",_div:"Mountain West - Mountain",_bye:0,_record:new _overallRecord() },
    { _ico:"i(117)",_team:"Utah State",_conf:"Mountain West Conference",_div:"Mountain West - Mountain",_bye:0,_record:new _overallRecord() },
    { _ico:"i(118)",_team:"San Diego State",_conf:"Mountain West Conference",_div:"Mountain West - West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(119)",_team:"Hawaii",_conf:"Mountain West Conference",_div:"Mountain West - West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(120)",_team:"Nevada",_conf:"Mountain West Conference",_div:"Mountain West - West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(121)",_team:"UNLV",_conf:"Mountain West Conference",_div:"Mountain West - West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(122)",_team:"San Jose State",_conf:"Mountain West Conference",_div:"Mountain West - West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(123)",_team:"Fresno State",_conf:"Mountain West Conference",_div:"Mountain West - West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(124)",_team:"Washington",_conf:"Pac-12 Conference",_div:"Pac 12 - North",_bye:0,_record:new _overallRecord() },
    { _ico:"i(125)",_team:"Washington State",_conf:"Pac-12 Conference",_div:"Pac 12 - North",_bye:0,_record:new _overallRecord() },
    { _ico:"i(126)",_team:"Stanford",_conf:"Pac-12 Conference",_div:"Pac 12 - North",_bye:0,_record:new _overallRecord() },
    { _ico:"i(127)",_team:"Oregon State",_conf:"Pac-12 Conference",_div:"Pac 12 - North",_bye:0,_record:new _overallRecord() },
    { _ico:"i(128)",_team:"California",_conf:"Pac-12 Conference",_div:"Pac 12 - North",_bye:0,_record:new _overallRecord() },
    { _ico:"i(129)",_team:"Oregon",_conf:"Pac-12 Conference",_div:"Pac 12 - North",_bye:0,_record:new _overallRecord() },
    { _ico:"i(130)",_team:"Arizona State",_conf:"Pac-12 Conference",_div:"Pac 12 - South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(131)",_team:"Utah",_conf:"Pac-12 Conference",_div:"Pac 12 - South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(132)",_team:"Colorado",_conf:"Pac-12 Conference",_div:"Pac 12 - South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(133)",_team:"USC",_conf:"Pac-12 Conference",_div:"Pac 12 - South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(134)",_team:"UCLA",_conf:"Pac-12 Conference",_div:"Pac 12 - South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(135)",_team:"Arizona",_conf:"Pac-12 Conference",_div:"Pac 12 - South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(136)",_team:"Tennessee",_conf:"Southeastern Conference (SEC)",_div:"SEC East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(137)",_team:"Florida",_conf:"Southeastern Conference (SEC)",_div:"SEC East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(138)",_team:"Georgia",_conf:"Southeastern Conference (SEC)",_div:"SEC East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(139)",_team:"Kentucky",_conf:"Southeastern Conference (SEC)",_div:"SEC East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(140)",_team:"South Carolina",_conf:"Southeastern Conference (SEC)",_div:"SEC East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(141)",_team:"Missouri",_conf:"Southeastern Conference (SEC)",_div:"SEC East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(142)",_team:"Vanderbilt",_conf:"Southeastern Conference (SEC)",_div:"SEC East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(143)",_team:"Texas A&M",_conf:"Southeastern Conference (SEC)",_div:"SEC West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(144)",_team:"Alabama",_conf:"Southeastern Conference (SEC)",_div:"SEC West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(145)",_team:"Auburn",_conf:"Southeastern Conference (SEC)",_div:"SEC West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(146)",_team:"LSU",_conf:"Southeastern Conference (SEC)",_div:"SEC West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(147)",_team:"Ole Miss",_conf:"Southeastern Conference (SEC)",_div:"SEC West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(148)",_team:"Mississippi State",_conf:"Southeastern Conference (SEC)",_div:"SEC West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(149)",_team:"Arkansas",_conf:"Southeastern Conference (SEC)",_div:"SEC West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(150)",_team:"Troy",_conf:"Sun Belt Conference",_div:"Sun Belt",_bye:0,_record:new _overallRecord() },
    { _ico:"i(151)",_team:"Appalachian State",_conf:"Sun Belt Conference",_div:"Sun Belt",_bye:0,_record:new _overallRecord() },
    { _ico:"i(152)",_team:"Arkansas State",_conf:"Sun Belt Conference",_div:"Sun Belt",_bye:0,_record:new _overallRecord() },
    { _ico:"i(153)",_team:"Georgia Southern",_conf:"Sun Belt Conference",_div:"Sun Belt",_bye:0,_record:new _overallRecord() },
    { _ico:"i(154)",_team:"Idaho",_conf:"Sun Belt Conference",_div:"Sun Belt",_bye:0,_record:new _overallRecord() },
    { _ico:"i(155)",_team:"New Mexico State",_conf:"Sun Belt Conference",_div:"Sun Belt",_bye:0,_record:new _overallRecord() },
    { _ico:"i(156)",_team:"Georgia State",_conf:"Sun Belt Conference",_div:"Sun Belt",_bye:0,_record:new _overallRecord() },
    { _ico:"i(157)",_team:"Louisiana Lafayette",_conf:"Sun Belt Conference",_div:"Sun Belt",_bye:0,_record:new _overallRecord() },
    { _ico:"i(158)",_team:"Texas State",_conf:"Sun Belt Conference",_div:"Sun Belt",_bye:0,_record:new _overallRecord() },
    { _ico:"i(159)",_team:"South Alabama",_conf:"Sun Belt Conference",_div:"Sun Belt",_bye:0,_record:new _overallRecord() },
    { _ico:"i(160)",_team:"Louisiana Monroe",_conf:"Sun Belt Conference",_div:"Sun Belt",_bye:0,_record:new _overallRecord() },
  ],

  [ // NCAA DIV I-AA
    { _ico:"i(23)",_team:"Eastern Washington",_conf:"Big Sky Conference",_div:"Big Sky Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(24)",_team:"North Dakota",_conf:"Big Sky Conference",_div:"Big Sky Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(25)",_team:"Weber State",_conf:"Big Sky Conference",_div:"Big Sky Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(26)",_team:"Southern Utah",_conf:"Big Sky Conference",_div:"Big Sky Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(27)",_team:"Montana",_conf:"Big Sky Conference",_div:"Big Sky Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(28)",_team:"Cal Poly",_conf:"Big Sky Conference",_div:"Big Sky Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(29)",_team:"Northern Colorado",_conf:"Big Sky Conference",_div:"Big Sky Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(30)",_team:"Idaho State",_conf:"Big Sky Conference",_div:"Big Sky Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(31)",_team:"Northern Arizona",_conf:"Big Sky Conference",_div:"Big Sky Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(32)",_team:"Portland State",_conf:"Big Sky Conference",_div:"Big Sky Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(33)",_team:"Sacramento State",_conf:"Big Sky Conference",_div:"Big Sky Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(34)",_team:"Montana State",_conf:"Big Sky Conference",_div:"Big Sky Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(35)",_team:"UC Davis",_conf:"Big Sky Conference",_div:"Big Sky Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(36)",_team:"Charleston Southern",_conf:"Big South Conference",_div:"Big South Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(37)",_team:"Gardner-Webb",_conf:"Big South Conference",_div:"Big South Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(38)",_team:"Presbyterian College",_conf:"Big South Conference",_div:"Big South Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(39)",_team:"Monmouth",_conf:"Big South Conference",_div:"Big South Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(40)",_team:"Kennesaw State",_conf:"Big South Conference",_div:"Big South Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(41)",_team:"Liberty",_conf:"Big South Conference",_div:"Big South Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(42)",_team:"James Madison",_conf:"Colonial Athletic Association",_div:"Colonial Athletic Association",_bye:0,_record:new _overallRecord() },
    { _ico:"i(43)",_team:"Villanova	",_conf:"Colonial Athletic Association",_div:"Colonial Athletic Association",_bye:0,_record:new _overallRecord() },
    { _ico:"i(44)",_team:"New Hampshire",_conf:"Colonial Athletic Association",_div:"Colonial Athletic Association",_bye:0,_record:new _overallRecord() },
    { _ico:"i(45)",_team:"Stony Brook",_conf:"Colonial Athletic Association",_div:"Colonial Athletic Association",_bye:0,_record:new _overallRecord() },
    { _ico:"i(46)",_team:"Richmond",_conf:"Colonial Athletic Association",_div:"Colonial Athletic Association",_bye:0,_record:new _overallRecord() },
    { _ico:"i(47)",_team:"Albany",_conf:"Colonial Athletic Association",_div:"Colonial Athletic Association",_bye:0,_record:new _overallRecord() },
    { _ico:"i(48)",_team:"Maine",_conf:"Colonial Athletic Association",_div:"Colonial Athletic Association",_bye:0,_record:new _overallRecord() },
    { _ico:"i(49)",_team:"Elon",_conf:"Colonial Athletic Association",_div:"Colonial Athletic Association",_bye:0,_record:new _overallRecord() },
    { _ico:"i(50)",_team:"Delaware",_conf:"Colonial Athletic Association",_div:"Colonial Athletic Association",_bye:0,_record:new _overallRecord() },
    { _ico:"i(51)",_team:"William & Mary",_conf:"Colonial Athletic Association",_div:"Colonial Athletic Association",_bye:0,_record:new _overallRecord() },
    { _ico:"i(52)",_team:"Towson",_conf:"Colonial Athletic Association",_div:"Colonial Athletic Association",_bye:0,_record:new _overallRecord() },
    { _ico:"i(53)",_team:"Rhode Island",_conf:"Colonial Athletic Association",_div:"Colonial Athletic Association",_bye:0,_record:new _overallRecord() },
    { _ico:"i(54)",_team:"Coastal Carolina",_conf:"FCS Independents",_div:"FCS Independents",_bye:0,_record:new _overallRecord() },
    { _ico:"i(55)",_team:"Harvard",_conf:"Ivy League",_div:"Ivy League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(56)",_team:"Princeton",_conf:"Ivy League",_div:"Ivy League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(57)",_team:"Penn",_conf:"Ivy League",_div:"Ivy League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(58)",_team:"Cornell",_conf:"Ivy League",_div:"Ivy League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(59)",_team:"Yale",_conf:"Ivy League",_div:"Ivy League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(60)",_team:"Brown",_conf:"Ivy League",_div:"Ivy League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(61)",_team:"Columbia",_conf:"Ivy League",_div:"Ivy League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(62)",_team:"Dartmouth",_conf:"Ivy League",_div:"Ivy League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(63)",_team:"North Carolina Central",_conf:"Mid-Eastern Athletic Conference",_div:"Mid-Eastern Athletic Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(64)",_team:"North Carolina A&T",_conf:"Mid-Eastern Athletic Conference",_div:"Mid-Eastern Athletic Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(65)",_team:"Morgan State",_conf:"Mid-Eastern Athletic Conference",_div:"Mid-Eastern Athletic Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(66)",_team:"South Carolina State",_conf:"Mid-Eastern Athletic Conference",_div:"Mid-Eastern Athletic Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(67)",_team:"Hampton",_conf:"Mid-Eastern Athletic Conference",_div:"Mid-Eastern Athletic Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(68)",_team:"Savannah State",_conf:"Mid-Eastern Athletic Conference",_div:"Mid-Eastern Athletic Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(69)",_team:"Florida A&M",_conf:"Mid-Eastern Athletic Conference",_div:"Mid-Eastern Athletic Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(70)",_team:"Howard",_conf:"Mid-Eastern Athletic Conference",_div:"Mid-Eastern Athletic Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(71)",_team:"Delaware State",_conf:"Mid-Eastern Athletic Conference",_div:"Mid-Eastern Athletic Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(72)",_team:"Bethune-Cookman",_conf:"Mid-Eastern Athletic Conference",_div:"Mid-Eastern Athletic Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(73)",_team:"Norfolk State",_conf:"Mid-Eastern Athletic Conference",_div:"Mid-Eastern Athletic Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(74)",_team:"North Dakota State",_conf:"Missouri Valley Football Conference",_div:"Missouri Valley Football Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(75)",_team:"Youngstown State",_conf:"Missouri Valley Football Conference",_div:"Missouri Valley Football Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(76)",_team:"South Dakota State",_conf:"Missouri Valley Football Conference",_div:"Missouri Valley Football Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(77)",_team:"Western Illinois",_conf:"Missouri Valley Football Conference",_div:"Missouri Valley Football Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(78)",_team:"Missouri State",_conf:"Missouri Valley Football Conference",_div:"Missouri Valley Football Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(79)",_team:"South Dakota",_conf:"Missouri Valley Football Conference",_div:"Missouri Valley Football Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(80)",_team:"Northern Iowa",_conf:"Missouri Valley Football Conference",_div:"Missouri Valley Football Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(81)",_team:"Indiana State",_conf:"Missouri Valley Football Conference",_div:"Missouri Valley Football Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(82)",_team:"Southern Illinois",_conf:"Missouri Valley Football Conference",_div:"Missouri Valley Football Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(83)",_team:"Illinois State ",_conf:"Missouri Valley Football Conference",_div:"Missouri Valley Football Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(84)",_team:"Wagner",_conf:"Northeast Conference",_div:"Northeast Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(85)",_team:"St Francis (PA)",_conf:"Northeast Conference",_div:"Northeast Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(86)",_team:"Bryant",_conf:"Northeast Conference",_div:"Northeast Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(87)",_team:"Sacred Heart",_conf:"Northeast Conference",_div:"Northeast Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(88)",_team:"Central Connecticut",_conf:"Northeast Conference",_div:"Northeast Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(89)",_team:"Robert Morris",_conf:"Northeast Conference",_div:"Northeast Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(90)",_team:"Duquesne",_conf:"Northeast Conference",_div:"Northeast Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(91)",_team:"Jacksonville State",_conf:"Ohio Valley Conference",_div:"Ohio Valley Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(92)",_team:"Eastern Illinois",_conf:"Ohio Valley Conference",_div:"Ohio Valley Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(93)",_team:"Tennessee-Martin",_conf:"Ohio Valley Conference",_div:"Ohio Valley Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(94)",_team:"Southeast Missouri State",_conf:"Ohio Valley Conference",_div:"Ohio Valley Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(95)",_team:"Tennessee Tech",_conf:"Ohio Valley Conference",_div:"Ohio Valley Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(96)",_team:"Tennessee State",_conf:"Ohio Valley Conference",_div:"Ohio Valley Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(97)",_team:"Eastern Kentucky",_conf:"Ohio Valley Conference",_div:"Ohio Valley Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(98)",_team:"Murray State",_conf:"Ohio Valley Conference",_div:"Ohio Valley Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(99)",_team:"Austin Peay",_conf:"Ohio Valley Conference",_div:"Ohio Valley Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(100)",_team:"Lehigh",_conf:"Patriot League",_div:"Patriot League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(101)",_team:"Fordham",_conf:"Patriot League",_div:"Patriot League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(102)",_team:"Bucknell",_conf:"Patriot League",_div:"Patriot League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(103)",_team:"Holy Cross",_conf:"Patriot League",_div:"Patriot League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(104)",_team:"Colgate",_conf:"Patriot League",_div:"Patriot League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(105)",_team:"Lafayette",_conf:"Patriot League",_div:"Patriot League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(106)",_team:"Georgetown",_conf:"Patriot League",_div:"Patriot League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(107)",_team:"San Diego",_conf:"Pioneer Football League",_div:"Pioneer Football League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(108)",_team:"Marist",_conf:"Pioneer Football League",_div:"Pioneer Football League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(109)",_team:"Jacksonville",_conf:"Pioneer Football League",_div:"Pioneer Football League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(110)",_team:"Dayton",_conf:"Pioneer Football League",_div:"Pioneer Football League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(111)",_team:"Drake",_conf:"Pioneer Football League",_div:"Pioneer Football League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(112)",_team:"Campbell",_conf:"Pioneer Football League",_div:"Pioneer Football League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(113)",_team:"Stetson",_conf:"Pioneer Football League",_div:"Pioneer Football League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(114)",_team:"Morehead State",_conf:"Pioneer Football League",_div:"Pioneer Football League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(115)",_team:"Valparaiso",_conf:"Pioneer Football League",_div:"Pioneer Football League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(116)",_team:"Butler",_conf:"Pioneer Football League",_div:"Pioneer Football League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(117)",_team:"Davidson",_conf:"Pioneer Football League",_div:"Pioneer Football League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(118)",_team:"Chattanooga",_conf:"Southern Conference",_div:"Southern Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(119)",_team:"The Citadel",_conf:"Southern Conference",_div:"Southern Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(120)",_team:"Samford",_conf:"Southern Conference",_div:"Southern Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(121)",_team:"Wofford",_conf:"Southern Conference",_div:"Southern Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(122)",_team:"VMI",_conf:"Southern Conference",_div:"Southern Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(123)",_team:"Mercer",_conf:"Southern Conference",_div:"Southern Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(124)",_team:"East Tenn. St.",_conf:"Southern Conference",_div:"Southern Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(125)",_team:"Western Carolina",_conf:"Southern Conference",_div:"Southern Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(126)",_team:"Furman",_conf:"Southern Conference",_div:"Southern Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(127)",_team:"Sam Houston State",_conf:"Southland Conference",_div:"Southland Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(128)",_team:"Central Arkansas",_conf:"Southland Conference",_div:"Southland Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(129)",_team:"Lamar",_conf:"Southland Conference",_div:"Southland Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(130)",_team:"Nicholls",_conf:"Southland Conference",_div:"Southland Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(131)",_team:"Southeastern Louisiana",_conf:"Southland Conference",_div:"Southland Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(132)",_team:"Stephen F Austin",_conf:"Southland Conference",_div:"Southland Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(133)",_team:"McNeese",_conf:"Southland Conference",_div:"Southland Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(134)",_team:"Houston Baptist",_conf:"Southland Conference",_div:"Southland Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(135)",_team:"Incarnate Word",_conf:"Southland Conference",_div:"Southland Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(136)",_team:"Northwestern State",_conf:"Southland Conference",_div:"Southland Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(137)",_team:"Abilene Christian",_conf:"Southland Conference",_div:"Southland Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(138)",_team:"Jackson State",_conf:"Southwestern Athletic Conference",_div:"Southwestern Athletic - East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(139)",_team:"Alcorn State",_conf:"Southwestern Athletic Conference",_div:"Southwestern Athletic - East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(140)",_team:"Alabama A&M",_conf:"Southwestern Athletic Conference",_div:"Southwestern Athletic - East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(141)",_team:"Alabama State",_conf:"Southwestern Athletic Conference",_div:"Southwestern Athletic - East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(142)",_team:"Mississippi Valley State",_conf:"Southwestern Athletic Conference",_div:"Southwestern Athletic - East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(143)",_team:"Grambling State",_conf:"Southwestern Athletic Conference",_div:"Southwestern Athletic - West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(144)",_team:"Southern",_conf:"Southwestern Athletic Conference",_div:"Southwestern Athletic - West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(145)",_team:"Prairie View",_conf:"Southwestern Athletic Conference",_div:"Southwestern Athletic - West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(146)",_team:"Texas Southern",_conf:"Southwestern Athletic Conference",_div:"Southwestern Athletic - West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(147)",_team:"Arkansas-Pine Bluff",_conf:"Southwestern Athletic Conference",_div:"Southwestern Athletic - West",_bye:0,_record:new _overallRecord() },
  ],

  [ // NCAA DIV II
    { _ico:"i(26)",_team:"Virginia Union",_conf:"CIAA",_div:"North",_bye:0,_record:new _overallRecord() },
    { _ico:"i(27)",_team:"Bowie State",_conf:"CIAA",_div:"North",_bye:0,_record:new _overallRecord() },
    { _ico:"i(28)",_team:"Chowan",_conf:"CIAA",_div:"North",_bye:0,_record:new _overallRecord() },
    { _ico:"i(29)",_team:"Virginia State",_conf:"CIAA",_div:"North",_bye:0,_record:new _overallRecord() },
    { _ico:"i(30)",_team:"Elizabeth City State",_conf:"CIAA",_div:"North",_bye:0,_record:new _overallRecord() },
    { _ico:"i(31)",_team:"Lincoln (PA)",_conf:"CIAA",_div:"North",_bye:0,_record:new _overallRecord() },
    { _ico:"i(32)",_team:"Winston-Salem",_conf:"CIAA",_div:"South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(33)",_team:"St. Augustine's",_conf:"CIAA",_div:"South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(34)",_team:"Johnson C Smith",_conf:"CIAA",_div:"South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(35)",_team:"Fayetteville State",_conf:"CIAA",_div:"South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(36)",_team:"Livingstone",_conf:"CIAA",_div:"South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(37)",_team:"Shaw",_conf:"CIAA",_div:"South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(38)",_team:"Grand Valley State",_conf:"GLIAC",_div:"GLIAC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(39)",_team:"Wayne State (MI)",_conf:"GLIAC",_div:"GLIAC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(40)",_team:"Ashland",_conf:"GLIAC",_div:"GLIAC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(41)",_team:"Ferris State",_conf:"GLIAC",_div:"GLIAC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(42)",_team:"Saginaw Valley",_conf:"GLIAC",_div:"GLIAC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(43)",_team:"Tiffin",_conf:"GLIAC",_div:"GLIAC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(44)",_team:"Northern Michigan",_conf:"GLIAC",_div:"GLIAC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(45)",_team:"Ohio Dominican",_conf:"GLIAC",_div:"GLIAC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(46)",_team:"Hillsdale",_conf:"GLIAC",_div:"GLIAC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(47)",_team:"Michigan Tech",_conf:"GLIAC",_div:"GLIAC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(48)",_team:"Findlay",_conf:"GLIAC",_div:"GLIAC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(49)",_team:"Northwood (MI)",_conf:"GLIAC",_div:"GLIAC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(50)",_team:"Lake Erie College",_conf:"GLIAC",_div:"GLIAC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(51)",_team:"Walsh",_conf:"GLIAC",_div:"GLIAC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(52)",_team:"Harding",_conf:"Great American Conference",_div:"Great American Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(53)",_team:"Henderson State",_conf:"Great American Conference",_div:"Great American Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(54)",_team:"Southern Arkansas",_conf:"Great American Conference",_div:"Great American Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(55)",_team:"Southeastern Oklahoma",_conf:"Great American Conference",_div:"Great American Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(56)",_team:"Arkansas Tech",_conf:"Great American Conference",_div:"Great American Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(57)",_team:"Ouachita Baptist",_conf:"Great American Conference",_div:"Great American Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(58)",_team:"Arkansas-Monticello",_conf:"Great American Conference",_div:"Great American Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(59)",_team:"Northwestern Oklahoma State",_conf:"Great American Conference",_div:"Great American Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(60)",_team:"Oklahoma Baptist",_conf:"Great American Conference",_div:"Great American Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(61)",_team:"Southwestern Oklahoma",_conf:"Great American Conference",_div:"Great American Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(62)",_team:"East Central",_conf:"Great American Conference",_div:"Great American Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(63)",_team:"Southern Nazarene",_conf:"Great American Conference",_div:"Great American Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(64)",_team:"Truman State",_conf:"Great Lakes",_div:"Great Lakes",_bye:0,_record:new _overallRecord() },
    { _ico:"i(65)",_team:"Southwest Baptist",_conf:"Great Lakes",_div:"Great Lakes",_bye:0,_record:new _overallRecord() },
    { _ico:"i(66)",_team:"St. Joseph's (IN)",_conf:"Great Lakes",_div:"Great Lakes",_bye:0,_record:new _overallRecord() },
    { _ico:"i(67)",_team:"Missouri S&T",_conf:"Great Lakes",_div:"Great Lakes",_bye:0,_record:new _overallRecord() },
    { _ico:"i(68)",_team:"Quincy",_conf:"Great Lakes",_div:"Great Lakes",_bye:0,_record:new _overallRecord() },
    { _ico:"i(69)",_team:"McKendree",_conf:"Great Lakes",_div:"Great Lakes",_bye:0,_record:new _overallRecord() },
    { _ico:"i(70)",_team:"Indianapolis",_conf:"Great Lakes",_div:"Great Lakes",_bye:0,_record:new _overallRecord() },
    { _ico:"i(71)",_team:"Lincoln (MO)",_conf:"Great Lakes",_div:"Great Lakes",_bye:0,_record:new _overallRecord() },
    { _ico:"i(72)",_team:"William Jewell College",_conf:"Great Lakes",_div:"Great Lakes",_bye:0,_record:new _overallRecord() },
    { _ico:"i(73)",_team:"Alderson-Broaddus",_conf:"Great Midwest Athletic Conference",_div:"Great Midwest Athletic Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(74)",_team:"Kentucky Wesleyan",_conf:"Great Midwest Athletic Conference",_div:"Great Midwest Athletic Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(75)",_team:"Malone",_conf:"Great Midwest Athletic Conference",_div:"Great Midwest Athletic Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(76)",_team:"Azusa Pacific",_conf:"Great Northwest",_div:"Great Northwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(77)",_team:"Central Washington",_conf:"Great Northwest",_div:"Great Northwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(78)",_team:"Western Oregon",_conf:"Great Northwest",_div:"Great Northwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(79)",_team:"Humboldt State",_conf:"Great Northwest",_div:"Great Northwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(80)",_team:"South Dakota Mines",_conf:"Great Northwest",_div:"Great Northwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(81)",_team:"Simon Fraser",_conf:"Great Northwest",_div:"Great Northwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(82)",_team:"North Alabama",_conf:"Gulf South",_div:"Gulf South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(83)",_team:"West Alabama",_conf:"Gulf South",_div:"Gulf South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(84)",_team:"Valdosta State",_conf:"Gulf South",_div:"Gulf South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(85)",_team:"West Florida",_conf:"Gulf South",_div:"Gulf South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(86)",_team:"Florida Tech",_conf:"Gulf South",_div:"Gulf South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(87)",_team:"Delta State",_conf:"Gulf South",_div:"Gulf South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(88)",_team:"West Georgia",_conf:"Gulf South",_div:"Gulf South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(89)",_team:"Shorter",_conf:"Gulf South",_div:"Gulf South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(90)",_team:"Mississippi College",_conf:"Gulf South",_div:"Gulf South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(91)",_team:"UNC Pembroke",_conf:"Independent DII",_div:"Independent DII",_bye:0,_record:new _overallRecord() },
    { _ico:"i(92)",_team:"Limestone",_conf:"Independent DII",_div:"Independent DII",_bye:0,_record:new _overallRecord() },
    { _ico:"i(93)",_team:"OK Panhandle St",_conf:"Independent DII",_div:"Independent DII",_bye:0,_record:new _overallRecord() },
    { _ico:"i(94)",_team:"North Greenville",_conf:"Independent DII",_div:"Independent DII",_bye:0,_record:new _overallRecord() },
    { _ico:"i(95)",_team:"Midwestern State",_conf:"Lone Star",_div:"Lone Star",_bye:0,_record:new _overallRecord() },
    { _ico:"i(96)",_team:"Eastern New Mexico",_conf:"Lone Star",_div:"Lone Star",_bye:0,_record:new _overallRecord() },
    { _ico:"i(97)",_team:"Texas A&M-Commerce",_conf:"Lone Star",_div:"Lone Star",_bye:0,_record:new _overallRecord() },
    { _ico:"i(98)",_team:"Tarleton State",_conf:"Lone Star",_div:"Lone Star",_bye:0,_record:new _overallRecord() },
    { _ico:"i(99)",_team:"West Texas A&M",_conf:"Lone Star",_div:"Lone Star",_bye:0,_record:new _overallRecord() },
    { _ico:"i(100)",_team:"Angelo State",_conf:"Lone Star",_div:"Lone Star",_bye:0,_record:new _overallRecord() },
    { _ico:"i(101)",_team:"Texas A&M-Kingsville",_conf:"Lone Star",_div:"Lone Star",_bye:0,_record:new _overallRecord() },
    { _ico:"i(102)",_team:"Western New Mexico",_conf:"Lone Star",_div:"Lone Star",_bye:0,_record:new _overallRecord() },
    { _ico:"i(103)",_team:"University of Texas of the Permian Basin",_conf:"Lone Star",_div:"Lone Star",_bye:0,_record:new _overallRecord() },
    { _ico:"i(104)",_team:"Northwest Missouri State",_conf:"Mid America",_div:"Mid America",_bye:0,_record:new _overallRecord() },
    { _ico:"i(105)",_team:"Emporia State",_conf:"Mid America",_div:"Mid America",_bye:0,_record:new _overallRecord() },
    { _ico:"i(106)",_team:"Fort Hays State",_conf:"Mid America",_div:"Mid America",_bye:0,_record:new _overallRecord() },
    { _ico:"i(107)",_team:"Central Missouri State",_conf:"Mid America",_div:"Mid America",_bye:0,_record:new _overallRecord() },
    { _ico:"i(108)",_team:"Pittsburg State",_conf:"Mid America",_div:"Mid America",_bye:0,_record:new _overallRecord() },
    { _ico:"i(109)",_team:"Missouri Western",_conf:"Mid America",_div:"Mid America",_bye:0,_record:new _overallRecord() },
    { _ico:"i(110)",_team:"Washburn",_conf:"Mid America",_div:"Mid America",_bye:0,_record:new _overallRecord() },
    { _ico:"i(111)",_team:"Northeastern State",_conf:"Mid America",_div:"Mid America",_bye:0,_record:new _overallRecord() },
    { _ico:"i(112)",_team:"Lindenwood",_conf:"Mid America",_div:"Mid America",_bye:0,_record:new _overallRecord() },
    { _ico:"i(113)",_team:"Central Oklahoma",_conf:"Mid America",_div:"Mid America",_bye:0,_record:new _overallRecord() },
    { _ico:"i(114)",_team:"Missouri Southern State",_conf:"Mid America",_div:"Mid America",_bye:0,_record:new _overallRecord() },
    { _ico:"i(115)",_team:"Nebraska-Kearney",_conf:"Mid America",_div:"Mid America",_bye:0,_record:new _overallRecord() },
    { _ico:"i(116)",_team:"Fairmont State",_conf:"Mountain East Conference",_div:"Mountain East Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(117)",_team:"Shepherd",_conf:"Mountain East Conference",_div:"Mountain East Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(118)",_team:"Notre Dame College",_conf:"Mountain East Conference",_div:"Mountain East Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(119)",_team:"UVA-Wise",_conf:"Mountain East Conference",_div:"Mountain East Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(120)",_team:"West Liberty",_conf:"Mountain East Conference",_div:"Mountain East Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(121)",_team:"Glenville State",_conf:"Mountain East Conference",_div:"Mountain East Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(122)",_team:"Concord",_conf:"Mountain East Conference",_div:"Mountain East Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(123)",_team:"Charleston (WV)",_conf:"Mountain East Conference",_div:"Mountain East Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(124)",_team:"Urbana",_conf:"Mountain East Conference",_div:"Mountain East Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(125)",_team:"WV Wesleyan",_conf:"Mountain East Conference",_div:"Mountain East Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(126)",_team:"WV State",_conf:"Mountain East Conference",_div:"Mountain East Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(127)",_team:"LIU Post",_conf:"Northeast 10",_div:"Northeast 10",_bye:0,_record:new _overallRecord() },
    { _ico:"i(128)",_team:"Assumption",_conf:"Northeast 10",_div:"Northeast 10",_bye:0,_record:new _overallRecord() },
    { _ico:"i(129)",_team:"New Haven",_conf:"Northeast 10",_div:"Northeast 10",_bye:0,_record:new _overallRecord() },
    { _ico:"i(130)",_team:"Southern Connecticut State",_conf:"Northeast 10",_div:"Northeast 10",_bye:0,_record:new _overallRecord() },
    { _ico:"i(131)",_team:"American International",_conf:"Northeast 10",_div:"Northeast 10",_bye:0,_record:new _overallRecord() },
    { _ico:"i(132)",_team:"Bentley",_conf:"Northeast 10",_div:"Northeast 10",_bye:0,_record:new _overallRecord() },
    { _ico:"i(133)",_team:"Stonehill",_conf:"Northeast 10",_div:"Northeast 10",_bye:0,_record:new _overallRecord() },
    { _ico:"i(134)",_team:"Merrimack",_conf:"Northeast 10",_div:"Northeast 10",_bye:0,_record:new _overallRecord() },
    { _ico:"i(135)",_team:"Pace",_conf:"Northeast 10",_div:"Northeast 10",_bye:0,_record:new _overallRecord() },
    { _ico:"i(136)",_team:"St. Anselm",_conf:"Northeast 10",_div:"Northeast 10",_bye:0,_record:new _overallRecord() },
    { _ico:"i(137)",_team:"Minnesota-Duluth",_conf:"Northern Sun",_div:"North",_bye:0,_record:new _overallRecord() },
    { _ico:"i(138)",_team:"Bemidji State",_conf:"Northern Sun",_div:"North",_bye:0,_record:new _overallRecord() },
    { _ico:"i(139)",_team:"Minnesota St-Moorhead",_conf:"Northern Sun",_div:"North",_bye:0,_record:new _overallRecord() },
    { _ico:"i(140)",_team:"Northern State",_conf:"Northern Sun",_div:"North",_bye:0,_record:new _overallRecord() },
    { _ico:"i(141)",_team:"St. Cloud State",_conf:"Northern Sun",_div:"North",_bye:0,_record:new _overallRecord() },
    { _ico:"i(142)",_team:"Minot State",_conf:"Northern Sun",_div:"North",_bye:0,_record:new _overallRecord() },
    { _ico:"i(143)",_team:"Minnesota-Crookston",_conf:"Northern Sun",_div:"North",_bye:0,_record:new _overallRecord() },
    { _ico:"i(144)",_team:"University of Mary",_conf:"Northern Sun",_div:"North",_bye:0,_record:new _overallRecord() },
    { _ico:"i(145)",_team:"Sioux Falls",_conf:"Northern Sun",_div:"South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(146)",_team:"Winona State",_conf:"Northern Sun",_div:"South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(147)",_team:"Augustana (SD)",_conf:"Northern Sun",_div:"South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(148)",_team:"Minnesota State",_conf:"Northern Sun",_div:"South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(149)",_team:"Southwest Minnesota State",_conf:"Northern Sun",_div:"South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(150)",_team:"Wayne State (NE)",_conf:"Northern Sun",_div:"South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(151)",_team:"Concordia-St. Paul",_conf:"Northern Sun",_div:"South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(152)",_team:"Upper Iowa",_conf:"Northern Sun",_div:"South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(153)",_team:"Shippensburg",_conf:"Pennsylvania State Athletic Conference",_div:"Penn State - Eastern",_bye:0,_record:new _overallRecord() },
    { _ico:"i(154)",_team:"Bloomsburg",_conf:"Pennsylvania State Athletic Conference",_div:"Penn State - Eastern",_bye:0,_record:new _overallRecord() },
    { _ico:"i(155)",_team:"East Stroudsburg",_conf:"Pennsylvania State Athletic Conference",_div:"Penn State - Eastern",_bye:0,_record:new _overallRecord() },
    { _ico:"i(156)",_team:"Kutztown",_conf:"Pennsylvania State Athletic Conference",_div:"Penn State - Eastern",_bye:0,_record:new _overallRecord() },
    { _ico:"i(157)",_team:"West Chester",_conf:"Pennsylvania State Athletic Conference",_div:"Penn State - Eastern",_bye:0,_record:new _overallRecord() },
    { _ico:"i(158)",_team:"Lock Haven",_conf:"Pennsylvania State Athletic Conference",_div:"Penn State - Eastern",_bye:0,_record:new _overallRecord() },
    { _ico:"i(159)",_team:"Cheyney",_conf:"Pennsylvania State Athletic Conference",_div:"Penn State - Eastern",_bye:0,_record:new _overallRecord() },
    { _ico:"i(160)",_team:"Millersville",_conf:"Pennsylvania State Athletic Conference",_div:"Penn State - Eastern",_bye:0,_record:new _overallRecord() },
    { _ico:"i(161)",_team:"California (PA)",_conf:"Pennsylvania State Athletic Conference",_div:"Penn State - Western",_bye:0,_record:new _overallRecord() },
    { _ico:"i(162)",_team:"Edinboro",_conf:"Pennsylvania State Athletic Conference",_div:"Penn State - Western",_bye:0,_record:new _overallRecord() },
    { _ico:"i(163)",_team:"Slippery Rock",_conf:"Pennsylvania State Athletic Conference",_div:"Penn State - Western",_bye:0,_record:new _overallRecord() },
    { _ico:"i(164)",_team:"Indiana (PA)",_conf:"Pennsylvania State Athletic Conference",_div:"Penn State - Western",_bye:0,_record:new _overallRecord() },
    { _ico:"i(165)",_team:"Seton Hill College",_conf:"Pennsylvania State Athletic Conference",_div:"Penn State - Western",_bye:0,_record:new _overallRecord() },
    { _ico:"i(166)",_team:"Gannon",_conf:"Pennsylvania State Athletic Conference",_div:"Penn State - Western",_bye:0,_record:new _overallRecord() },
    { _ico:"i(167)",_team:"Mercyhurst",_conf:"Pennsylvania State Athletic Conference",_div:"Penn State - Western",_bye:0,_record:new _overallRecord() },
    { _ico:"i(168)",_team:"Clarion",_conf:"Pennsylvania State Athletic Conference",_div:"Penn State - Western",_bye:0,_record:new _overallRecord() },
    { _ico:"i(169)",_team:"Black Hills State",_conf:"Rocky Mountain",_div:"Rocky Mountain",_bye:0,_record:new _overallRecord() },
    { _ico:"i(170)",_team:"Colorado Mesa",_conf:"Rocky Mountain",_div:"Rocky Mountain",_bye:0,_record:new _overallRecord() },
    { _ico:"i(171)",_team:"Western State",_conf:"Rocky Mountain",_div:"Rocky Mountain",_bye:0,_record:new _overallRecord() },
    { _ico:"i(172)",_team:"Colorado Mines",_conf:"Rocky Mountain",_div:"Rocky Mountain",_bye:0,_record:new _overallRecord() },
    { _ico:"i(173)",_team:"Colorado State-Pueblo",_conf:"Rocky Mountain",_div:"Rocky Mountain",_bye:0,_record:new _overallRecord() },
    { _ico:"i(174)",_team:"Chadron State",_conf:"Rocky Mountain",_div:"Rocky Mountain",_bye:0,_record:new _overallRecord() },
    { _ico:"i(175)",_team:"Adams State",_conf:"Rocky Mountain",_div:"Rocky Mountain",_bye:0,_record:new _overallRecord() },
    { _ico:"i(176)",_team:"Fort Lewis",_conf:"Rocky Mountain",_div:"Rocky Mountain",_bye:0,_record:new _overallRecord() },
    { _ico:"i(177)",_team:"Dixie State",_conf:"Rocky Mountain",_div:"Rocky Mountain",_bye:0,_record:new _overallRecord() },
    { _ico:"i(178)",_team:"New Mexico Highlands",_conf:"Rocky Mountain",_div:"Rocky Mountain",_bye:0,_record:new _overallRecord() },
    { _ico:"i(179)",_team:"Clark Atlanta",_conf:"SIAC",_div:"East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(180)",_team:"Albany State (GA)",_conf:"SIAC",_div:"East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(181)",_team:"Morehouse",_conf:"SIAC",_div:"East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(182)",_team:"Fort Valley State",_conf:"SIAC",_div:"East",_bye:0,_record:new _overallRecord() },
    { _ico:"i(183)",_team:"Tuskegee",_conf:"SIAC",_div:"West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(184)",_team:"Miles",_conf:"SIAC",_div:"West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(185)",_team:"Lane",_conf:"SIAC",_div:"West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(186)",_team:"Kentucky State",_conf:"SIAC",_div:"West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(187)",_team:"Central State",_conf:"SIAC",_div:"West",_bye:0,_record:new _overallRecord() },
    { _ico:"i(188)",_team:"Newberry",_conf:"South Atlantic",_div:"South Atlantic",_bye:0,_record:new _overallRecord() },
    { _ico:"i(189)",_team:"Lenoir-Rhyne",_conf:"South Atlantic",_div:"South Atlantic",_bye:0,_record:new _overallRecord() },
    { _ico:"i(190)",_team:"Wingate",_conf:"South Atlantic",_div:"South Atlantic",_bye:0,_record:new _overallRecord() },
    { _ico:"i(191)",_team:"Catawba",_conf:"South Atlantic",_div:"South Atlantic",_bye:0,_record:new _overallRecord() },
    { _ico:"i(192)",_team:"Carson-Newman",_conf:"South Atlantic",_div:"South Atlantic",_bye:0,_record:new _overallRecord() },
    { _ico:"i(193)",_team:"Tusculum",_conf:"South Atlantic",_div:"South Atlantic",_bye:0,_record:new _overallRecord() },
    { _ico:"i(194)",_team:"Mars Hill",_conf:"South Atlantic",_div:"South Atlantic",_bye:0,_record:new _overallRecord() },
    { _ico:"i(195)",_team:"Brevard College",_conf:"South Atlantic",_div:"South Atlantic",_bye:0,_record:new _overallRecord() },  
  ],

  [ // NCAA DIV III
    { _ico:"i(24)",_team:"Hardin-Simmons",_conf:"American Southwest",_div:"American Southwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(25)",_team:"Mary Hardin-Baylor",_conf:"American Southwest",_div:"American Southwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(26)",_team:"East Texas Baptist",_conf:"American Southwest",_div:"American Southwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(27)",_team:"Louisiana College",_conf:"American Southwest",_div:"American Southwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(28)",_team:"Belhaven College",_conf:"American Southwest",_div:"American Southwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(29)",_team:"Sul Ross State",_conf:"American Southwest",_div:"American Southwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(30)",_team:"McMurry",_conf:"American Southwest",_div:"American Southwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(31)",_team:"Howard Payne",_conf:"American Southwest",_div:"American Southwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(32)",_team:"Wheaton College (Ill)",_conf:"CCIW",_div:"CCIW",_bye:0,_record:new _overallRecord() },
    { _ico:"i(33)",_team:"North Central",_conf:"CCIW",_div:"CCIW",_bye:0,_record:new _overallRecord() },
    { _ico:"i(34)",_team:"Elmhurst",_conf:"CCIW",_div:"CCIW",_bye:0,_record:new _overallRecord() },
    { _ico:"i(35)",_team:"Illinois Wesleyan",_conf:"CCIW",_div:"CCIW",_bye:0,_record:new _overallRecord() },
    { _ico:"i(36)",_team:"Carthage",_conf:"CCIW",_div:"CCIW",_bye:0,_record:new _overallRecord() },
    { _ico:"i(37)",_team:"Millikin",_conf:"CCIW",_div:"CCIW",_bye:0,_record:new _overallRecord() },
    { _ico:"i(38)",_team:"Carroll (WI)",_conf:"CCIW",_div:"CCIW",_bye:0,_record:new _overallRecord() },
    { _ico:"i(39)",_team:"Augustana (IL)",_conf:"CCIW",_div:"CCIW",_bye:0,_record:new _overallRecord() },
    { _ico:"i(40)",_team:"North Park",_conf:"CCIW",_div:"CCIW",_bye:0,_record:new _overallRecord() },
    { _ico:"i(41)",_team:"Johns Hopkins",_conf:"Centennial",_div:"Centennial",_bye:0,_record:new _overallRecord() },
    { _ico:"i(42)",_team:"Muhlenberg",_conf:"Centennial",_div:"Centennial",_bye:0,_record:new _overallRecord() },
    { _ico:"i(43)",_team:"Franklin & Marshall",_conf:"Centennial",_div:"Centennial",_bye:0,_record:new _overallRecord() },
    { _ico:"i(44)",_team:"Moravian",_conf:"Centennial",_div:"Centennial",_bye:0,_record:new _overallRecord() },
    { _ico:"i(45)",_team:"Juniata",_conf:"Centennial",_div:"Centennial",_bye:0,_record:new _overallRecord() },
    { _ico:"i(46)",_team:"Susquehanna",_conf:"Centennial",_div:"Centennial",_bye:0,_record:new _overallRecord() },
    { _ico:"i(47)",_team:"Gettysburg",_conf:"Centennial",_div:"Centennial",_bye:0,_record:new _overallRecord() },
    { _ico:"i(48)",_team:"McDaniel College",_conf:"Centennial",_div:"Centennial",_bye:0,_record:new _overallRecord() },
    { _ico:"i(49)",_team:"Ursinus",_conf:"Centennial",_div:"Centennial",_bye:0,_record:new _overallRecord() },
    { _ico:"i(50)",_team:"Dickinson",_conf:"Centennial",_div:"Centennial",_bye:0,_record:new _overallRecord() },
    { _ico:"i(51)",_team:"Husson",_conf:"ECFC",_div:"ECFC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(52)",_team:"Castleton State College",_conf:"ECFC",_div:"ECFC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(53)",_team:"SUNY Maritime",_conf:"ECFC",_div:"ECFC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(54)",_team:"Becker College",_conf:"ECFC",_div:"ECFC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(55)",_team:"Mount Ida College",_conf:"ECFC",_div:"ECFC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(56)",_team:"Norwich",_conf:"ECFC",_div:"ECFC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(57)",_team:"Gallaudet",_conf:"ECFC",_div:"ECFC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(58)",_team:"Anna Maria College",_conf:"ECFC",_div:"ECFC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(59)",_team:"St. John Fisher",_conf:"Empire 8",_div:"Empire 8",_bye:0,_record:new _overallRecord() },
    { _ico:"i(60)",_team:"Alfred",_conf:"Empire 8",_div:"Empire 8",_bye:0,_record:new _overallRecord() },
    { _ico:"i(61)",_team:"Ithaca",_conf:"Empire 8",_div:"Empire 8",_bye:0,_record:new _overallRecord() },
    { _ico:"i(62)",_team:"Brockport State (NY)",_conf:"Empire 8",_div:"Empire 8",_bye:0,_record:new _overallRecord() },
    { _ico:"i(63)",_team:"Utica College",_conf:"Empire 8",_div:"Empire 8",_bye:0,_record:new _overallRecord() },
    { _ico:"i(64)",_team:"Buffalo State",_conf:"Empire 8",_div:"Empire 8",_bye:0,_record:new _overallRecord() },
    { _ico:"i(65)",_team:"SUNY Cortland",_conf:"Empire 8",_div:"Empire 8",_bye:0,_record:new _overallRecord() },
    { _ico:"i(66)",_team:"Hartwick",_conf:"Empire 8",_div:"Empire 8",_bye:0,_record:new _overallRecord() },
    { _ico:"i(67)",_team:"Morrisville State",_conf:"Empire 8",_div:"Empire 8",_bye:0,_record:new _overallRecord() },
    { _ico:"i(68)",_team:"Franklin",_conf:"Heartland",_div:"Heartland",_bye:0,_record:new _overallRecord() },
    { _ico:"i(69)",_team:"Rose-Hulman",_conf:"Heartland",_div:"Heartland",_bye:0,_record:new _overallRecord() },
    { _ico:"i(70)",_team:"Mount St. Joseph",_conf:"Heartland",_div:"Heartland",_bye:0,_record:new _overallRecord() },
    { _ico:"i(71)",_team:"Bluffton",_conf:"Heartland",_div:"Heartland",_bye:0,_record:new _overallRecord() },
    { _ico:"i(72)",_team:"Defiance",_conf:"Heartland",_div:"Heartland",_bye:0,_record:new _overallRecord() },
    { _ico:"i(73)",_team:"Hanover",_conf:"Heartland",_div:"Heartland",_bye:0,_record:new _overallRecord() },
    { _ico:"i(74)",_team:"Anderson (IN)",_conf:"Heartland",_div:"Heartland",_bye:0,_record:new _overallRecord() },
    { _ico:"i(75)",_team:"Earlham",_conf:"Heartland",_div:"Heartland",_bye:0,_record:new _overallRecord() },
    { _ico:"i(76)",_team:"Manchester",_conf:"Heartland",_div:"Heartland",_bye:0,_record:new _overallRecord() },
    { _ico:"i(77)",_team:"Apprentice School",_conf:"Independent DIII",_div:"Independent DIII",_bye:0,_record:new _overallRecord() },
    { _ico:"i(78)",_team:"Maranatha Baptist College",_conf:"Independent DIII",_div:"Independent DIII",_bye:0,_record:new _overallRecord() },
    { _ico:"i(79)",_team:"Finlandia University",_conf:"Independent DIII",_div:"Independent DIII",_bye:0,_record:new _overallRecord() },
    { _ico:"i(80)",_team:"Alfred State College",_conf:"Independent DIII",_div:"Independent DIII",_bye:0,_record:new _overallRecord() },
    { _ico:"i(81)",_team:"Coe",_conf:"Iowa",_div:"Iowa",_bye:0,_record:new _overallRecord() },
    { _ico:"i(82)",_team:"Dubuque",_conf:"Iowa",_div:"Iowa",_bye:0,_record:new _overallRecord() },
    { _ico:"i(83)",_team:"Central",_conf:"Iowa",_div:"Iowa",_bye:0,_record:new _overallRecord() },
    { _ico:"i(84)",_team:"Wartburg",_conf:"Iowa",_div:"Iowa",_bye:0,_record:new _overallRecord() },
    { _ico:"i(85)",_team:"Luther",_conf:"Iowa",_div:"Iowa",_bye:0,_record:new _overallRecord() },
    { _ico:"i(86)",_team:"Simpson College",_conf:"Iowa",_div:"Iowa",_bye:0,_record:new _overallRecord() },
    { _ico:"i(87)",_team:"Buena Vista",_conf:"Iowa",_div:"Iowa",_bye:0,_record:new _overallRecord() },
    { _ico:"i(88)",_team:"Nebraska Wesleyan University",_conf:"Iowa",_div:"Iowa",_bye:0,_record:new _overallRecord() },
    { _ico:"i(89)",_team:"Loras College",_conf:"Iowa",_div:"Iowa",_bye:0,_record:new _overallRecord() },
    { _ico:"i(90)",_team:"St Lawrence",_conf:"Liberty League",_div:"Liberty League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(91)",_team:"Hobart",_conf:"Liberty League",_div:"Liberty League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(92)",_team:"Rensselaer",_conf:"Liberty League",_div:"Liberty League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(93)",_team:"Merchant Marine",_conf:"Liberty League",_div:"Liberty League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(94)",_team:"Springfield",_conf:"Liberty League",_div:"Liberty League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(95)",_team:"Worcester Polytechnic",_conf:"Liberty League",_div:"Liberty League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(96)",_team:"Rochester",_conf:"Liberty League",_div:"Liberty League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(97)",_team:"Union",_conf:"Liberty League",_div:"Liberty League",_bye:0,_record:new _overallRecord() },
    { _ico:"i(98)",_team:"Bridgewater State",_conf:"Massachusetts State Collegiate Athletic Conference",_div:"Massachusetts State Collegiate Athletic Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(99)",_team:"Framingham State",_conf:"Massachusetts State Collegiate Athletic Conference",_div:"Massachusetts State Collegiate Athletic Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(100)",_team:"Plymouth State",_conf:"Massachusetts State Collegiate Athletic Conference",_div:"Massachusetts State Collegiate Athletic Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(101)",_team:"Mass Maritime",_conf:"Massachusetts State Collegiate Athletic Conference",_div:"Massachusetts State Collegiate Athletic Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(102)",_team:"UMass Dartmouth",_conf:"Massachusetts State Collegiate Athletic Conference",_div:"Massachusetts State Collegiate Athletic Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(103)",_team:"Westfield State",_conf:"Massachusetts State Collegiate Athletic Conference",_div:"Massachusetts State Collegiate Athletic Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(104)",_team:"Worcester State College",_conf:"Massachusetts State Collegiate Athletic Conference",_div:"Massachusetts State Collegiate Athletic Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(105)",_team:"Western Connecticut State",_conf:"Massachusetts State Collegiate Athletic Conference",_div:"Massachusetts State Collegiate Athletic Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(106)",_team:"Fitchburg State",_conf:"Massachusetts State Collegiate Athletic Conference",_div:"Massachusetts State Collegiate Athletic Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(107)",_team:"Olivet College",_conf:"Michigan",_div:"Michigan",_bye:0,_record:new _overallRecord() },
    { _ico:"i(108)",_team:"Trine",_conf:"Michigan",_div:"Michigan",_bye:0,_record:new _overallRecord() },
    { _ico:"i(109)",_team:"Adrian",_conf:"Michigan",_div:"Michigan",_bye:0,_record:new _overallRecord() },
    { _ico:"i(110)",_team:"Alma College",_conf:"Michigan",_div:"Michigan",_bye:0,_record:new _overallRecord() },
    { _ico:"i(111)",_team:"Hope",_conf:"Michigan",_div:"Michigan",_bye:0,_record:new _overallRecord() },
    { _ico:"i(112)",_team:"Kalamazoo",_conf:"Michigan",_div:"Michigan",_bye:0,_record:new _overallRecord() },
    { _ico:"i(113)",_team:"Albion",_conf:"Michigan",_div:"Michigan",_bye:0,_record:new _overallRecord() },
    { _ico:"i(114)",_team:"Stevenson",_conf:"Middle Atlantic States",_div:"Middle Atlantic States",_bye:0,_record:new _overallRecord() },
    { _ico:"i(115)",_team:"Widener",_conf:"Middle Atlantic States",_div:"Middle Atlantic States",_bye:0,_record:new _overallRecord() },
    { _ico:"i(116)",_team:"Delaware Valley",_conf:"Middle Atlantic States",_div:"Middle Atlantic States",_bye:0,_record:new _overallRecord() },
    { _ico:"i(117)",_team:"Albright",_conf:"Middle Atlantic States",_div:"Middle Atlantic States",_bye:0,_record:new _overallRecord() },
    { _ico:"i(118)",_team:"King's College (PA)",_conf:"Middle Atlantic States",_div:"Middle Atlantic States",_bye:0,_record:new _overallRecord() },
    { _ico:"i(119)",_team:"FDU-Florham",_conf:"Middle Atlantic States",_div:"Middle Atlantic States",_bye:0,_record:new _overallRecord() },
    { _ico:"i(120)",_team:"Wilkes",_conf:"Middle Atlantic States",_div:"Middle Atlantic States",_bye:0,_record:new _overallRecord() },
    { _ico:"i(121)",_team:"Lycoming",_conf:"Middle Atlantic States",_div:"Middle Atlantic States",_bye:0,_record:new _overallRecord() },
    { _ico:"i(122)",_team:"Lebanon Valley",_conf:"Middle Atlantic States",_div:"Middle Atlantic States",_bye:0,_record:new _overallRecord() },
    { _ico:"i(123)",_team:"Misericordia",_conf:"Middle Atlantic States",_div:"Middle Atlantic States",_bye:0,_record:new _overallRecord() },
    { _ico:"i(124)",_team:"Macalester",_conf:"Midwest",_div:"Midwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(125)",_team:"Monmouth (IL)",_conf:"Midwest",_div:"Midwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(126)",_team:"St. Norbert",_conf:"Midwest",_div:"Midwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(127)",_team:"Illinois College",_conf:"Midwest",_div:"Midwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(128)",_team:"Lake Forest",_conf:"Midwest",_div:"Midwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(129)",_team:"Beloit College",_conf:"Midwest",_div:"Midwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(130)",_team:"Lawrence",_conf:"Midwest",_div:"Midwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(131)",_team:"Cornell College (IA)",_conf:"Midwest",_div:"Midwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(132)",_team:"Ripon",_conf:"Midwest",_div:"Midwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(133)",_team:"Knox College",_conf:"Midwest",_div:"Midwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(134)",_team:"Carroll (WI)",_conf:"Midwest",_div:"Midwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(135)",_team:"Grinnell",_conf:"Midwest",_div:"Midwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(136)",_team:"St. Thomas (MN)",_conf:"Minnesota",_div:"Minnesota",_bye:0,_record:new _overallRecord() },
    { _ico:"i(137)",_team:"St. Johns (MN)",_conf:"Minnesota",_div:"Minnesota",_bye:0,_record:new _overallRecord() },
    { _ico:"i(138)",_team:"Hamline",_conf:"Minnesota",_div:"Minnesota",_bye:0,_record:new _overallRecord() },
    { _ico:"i(139)",_team:"Concordia (MN)",_conf:"Minnesota",_div:"Minnesota",_bye:0,_record:new _overallRecord() },
    { _ico:"i(140)",_team:"Bethel (MN)",_conf:"Minnesota",_div:"Minnesota",_bye:0,_record:new _overallRecord() },
    { _ico:"i(141)",_team:"Gustavus Adolphus",_conf:"Minnesota",_div:"Minnesota",_bye:0,_record:new _overallRecord() },
    { _ico:"i(142)",_team:"Augsburg",_conf:"Minnesota",_div:"Minnesota",_bye:0,_record:new _overallRecord() },
    { _ico:"i(143)",_team:"Carleton",_conf:"Minnesota",_div:"Minnesota",_bye:0,_record:new _overallRecord() },
    { _ico:"i(144)",_team:"St. Olaf College",_conf:"Minnesota",_div:"Minnesota",_bye:0,_record:new _overallRecord() },
    { _ico:"i(145)",_team:"Middlebury",_conf:"NESCAC",_div:"NESCAC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(146)",_team:"Trinity (CT)",_conf:"NESCAC",_div:"NESCAC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(147)",_team:"Tufts",_conf:"NESCAC",_div:"NESCAC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(148)",_team:"Amherst College",_conf:"NESCAC",_div:"NESCAC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(149)",_team:"Wesleyan",_conf:"NESCAC",_div:"NESCAC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(150)",_team:"Bates College",_conf:"NESCAC",_div:"NESCAC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(151)",_team:"Colby",_conf:"NESCAC",_div:"NESCAC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(152)",_team:"Bowdoin",_conf:"NESCAC",_div:"NESCAC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(153)",_team:"Hamilton",_conf:"NESCAC",_div:"NESCAC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(154)",_team:"Williams",_conf:"NESCAC",_div:"NESCAC",_bye:0,_record:new _overallRecord() },
    { _ico:"i(155)",_team:"Western New England",_conf:"New England",_div:"New England",_bye:0,_record:new _overallRecord() },
    { _ico:"i(156)",_team:"Salve Regina",_conf:"New England",_div:"New England",_bye:0,_record:new _overallRecord() },
    { _ico:"i(157)",_team:"Endicott College",_conf:"New England",_div:"New England",_bye:0,_record:new _overallRecord() },
    { _ico:"i(158)",_team:"Coast Guard",_conf:"New England",_div:"New England",_bye:0,_record:new _overallRecord() },
    { _ico:"i(159)",_team:"MIT",_conf:"New England",_div:"New England",_bye:0,_record:new _overallRecord() },
    { _ico:"i(160)",_team:"Curry",_conf:"New England",_div:"New England",_bye:0,_record:new _overallRecord() },
    { _ico:"i(161)",_team:"Nichols",_conf:"New England",_div:"New England",_bye:0,_record:new _overallRecord() },
    { _ico:"i(162)",_team:"Maine Maritime",_conf:"New England",_div:"New England",_bye:0,_record:new _overallRecord() },
    { _ico:"i(163)",_team:"Rowan",_conf:"New Jersey",_div:"New Jersey",_bye:0,_record:new _overallRecord() },
    { _ico:"i(164)",_team:"Christopher Newport",_conf:"New Jersey",_div:"New Jersey",_bye:0,_record:new _overallRecord() },
    { _ico:"i(165)",_team:"Frostburg State",_conf:"New Jersey",_div:"New Jersey",_bye:0,_record:new _overallRecord() },
    { _ico:"i(166)",_team:"Salisbury",_conf:"New Jersey",_div:"New Jersey",_bye:0,_record:new _overallRecord() },
    { _ico:"i(167)",_team:"Wesley College",_conf:"New Jersey",_div:"New Jersey",_bye:0,_record:new _overallRecord() },
    { _ico:"i(168)",_team:"Kean",_conf:"New Jersey",_div:"New Jersey",_bye:0,_record:new _overallRecord() },
    { _ico:"i(169)",_team:"Montclair State",_conf:"New Jersey",_div:"New Jersey",_bye:0,_record:new _overallRecord() },
    { _ico:"i(170)",_team:"William Paterson",_conf:"New Jersey",_div:"New Jersey",_bye:0,_record:new _overallRecord() },
    { _ico:"i(171)",_team:"Southern Virginia",_conf:"New Jersey",_div:"New Jersey",_bye:0,_record:new _overallRecord() },
    { _ico:"i(172)",_team:"College of New Jersey",_conf:"New Jersey",_div:"New Jersey",_bye:0,_record:new _overallRecord() },
    { _ico:"i(173)",_team:"Denison",_conf:"North Coast",_div:"North Coast",_bye:0,_record:new _overallRecord() },
    { _ico:"i(174)",_team:"Wittenberg",_conf:"North Coast",_div:"North Coast",_bye:0,_record:new _overallRecord() },
    { _ico:"i(175)",_team:"DePauw",_conf:"North Coast",_div:"North Coast",_bye:0,_record:new _overallRecord() },
    { _ico:"i(176)",_team:"Wabash College",_conf:"North Coast",_div:"North Coast",_bye:0,_record:new _overallRecord() },
    { _ico:"i(177)",_team:"Ohio Wesleyan",_conf:"North Coast",_div:"North Coast",_bye:0,_record:new _overallRecord() },
    { _ico:"i(178)",_team:"Kenyon",_conf:"North Coast",_div:"North Coast",_bye:0,_record:new _overallRecord() },
    { _ico:"i(179)",_team:"Wooster",_conf:"North Coast",_div:"North Coast",_bye:0,_record:new _overallRecord() },
    { _ico:"i(180)",_team:"Allegheny",_conf:"North Coast",_div:"North Coast",_bye:0,_record:new _overallRecord() },
    { _ico:"i(181)",_team:"Hiram",_conf:"North Coast",_div:"North Coast",_bye:0,_record:new _overallRecord() },
    { _ico:"i(182)",_team:"Oberlin",_conf:"North Coast",_div:"North Coast",_bye:0,_record:new _overallRecord() },
    { _ico:"i(183)",_team:"Benedictine (IL)",_conf:"Northern Athletics",_div:"Northern Athletics",_bye:0,_record:new _overallRecord() },
    { _ico:"i(184)",_team:"Aurora",_conf:"Northern Athletics",_div:"Northern Athletics",_bye:0,_record:new _overallRecord() },
    { _ico:"i(185)",_team:"Lakeland College",_conf:"Northern Athletics",_div:"Northern Athletics",_bye:0,_record:new _overallRecord() },
    { _ico:"i(186)",_team:"Wisconsin Lutheran",_conf:"Northern Athletics",_div:"Northern Athletics",_bye:0,_record:new _overallRecord() },
    { _ico:"i(187)",_team:"Concordia (IL)",_conf:"Northern Athletics",_div:"Northern Athletics",_bye:0,_record:new _overallRecord() },
    { _ico:"i(188)",_team:"Concordia (WI)",_conf:"Northern Athletics",_div:"Northern Athletics",_bye:0,_record:new _overallRecord() },
    { _ico:"i(189)",_team:"Rockford",_conf:"Northern Athletics",_div:"Northern Athletics",_bye:0,_record:new _overallRecord() },
    { _ico:"i(190)",_team:"Whitworth",_conf:"Northwest",_div:"Northwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(191)",_team:"Linfield",_conf:"Northwest",_div:"Northwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(192)",_team:"Pacific Lutheran",_conf:"Northwest",_div:"Northwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(193)",_team:"Willamette",_conf:"Northwest",_div:"Northwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(194)",_team:"George Fox University",_conf:"Northwest",_div:"Northwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(195)",_team:"Puget Sound",_conf:"Northwest",_div:"Northwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(196)",_team:"Pacific (OR)",_conf:"Northwest",_div:"Northwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(197)",_team:"Lewis & Clark",_conf:"Northwest",_div:"Northwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(198)",_team:"Mount Union",_conf:"Ohio",_div:"Ohio",_bye:0,_record:new _overallRecord() },
    { _ico:"i(199)",_team:"John Carroll",_conf:"Ohio",_div:"Ohio",_bye:0,_record:new _overallRecord() },
    { _ico:"i(200)",_team:"Capital",_conf:"Ohio",_div:"Ohio",_bye:0,_record:new _overallRecord() },
    { _ico:"i(201)",_team:"Heidelberg",_conf:"Ohio",_div:"Ohio",_bye:0,_record:new _overallRecord() },
    { _ico:"i(202)",_team:"Ohio Northern",_conf:"Ohio",_div:"Ohio",_bye:0,_record:new _overallRecord() },
    { _ico:"i(203)",_team:"Otterbein",_conf:"Ohio",_div:"Ohio",_bye:0,_record:new _overallRecord() },
    { _ico:"i(204)",_team:"Muskingum",_conf:"Ohio",_div:"Ohio",_bye:0,_record:new _overallRecord() },
    { _ico:"i(205)",_team:"Baldwin-Wallace",_conf:"Ohio",_div:"Ohio",_bye:0,_record:new _overallRecord() },
    { _ico:"i(206)",_team:"Marietta",_conf:"Ohio",_div:"Ohio",_bye:0,_record:new _overallRecord() },
    { _ico:"i(207)",_team:"Wilmington (OH)",_conf:"Ohio",_div:"Ohio",_bye:0,_record:new _overallRecord() },
    { _ico:"i(208)",_team:"Randolph-Macon",_conf:"Old Dominion",_div:"Old Dominion",_bye:0,_record:new _overallRecord() },
    { _ico:"i(209)",_team:"Washington & Lee",_conf:"Old Dominion",_div:"Old Dominion",_bye:0,_record:new _overallRecord() },
    { _ico:"i(210)",_team:"Guilford",_conf:"Old Dominion",_div:"Old Dominion",_bye:0,_record:new _overallRecord() },
    { _ico:"i(211)",_team:"Shenandoah",_conf:"Old Dominion",_div:"Old Dominion",_bye:0,_record:new _overallRecord() },
    { _ico:"i(212)",_team:"Bridgewater (VA)",_conf:"Old Dominion",_div:"Old Dominion",_bye:0,_record:new _overallRecord() },
    { _ico:"i(213)",_team:"Hampden-Sydney",_conf:"Old Dominion",_div:"Old Dominion",_bye:0,_record:new _overallRecord() },
    { _ico:"i(214)",_team:"Catholic University",_conf:"Old Dominion",_div:"Old Dominion",_bye:0,_record:new _overallRecord() },
    { _ico:"i(215)",_team:"Emory & Henry",_conf:"Old Dominion",_div:"Old Dominion",_bye:0,_record:new _overallRecord() },
    { _ico:"i(216)",_team:"Case Western Reserve",_conf:"Presidents",_div:"Presidents",_bye:0,_record:new _overallRecord() },
    { _ico:"i(217)",_team:"Thomas More",_conf:"Presidents",_div:"Presidents",_bye:0,_record:new _overallRecord() },
    { _ico:"i(218)",_team:"Washington & Jefferson",_conf:"Presidents",_div:"Presidents",_bye:0,_record:new _overallRecord() },
    { _ico:"i(219)",_team:"Westminster PA",_conf:"Presidents",_div:"Presidents",_bye:0,_record:new _overallRecord() },
    { _ico:"i(220)",_team:"St. Vincent",_conf:"Presidents",_div:"Presidents",_bye:0,_record:new _overallRecord() },
    { _ico:"i(221)",_team:"Carnegie Mellon",_conf:"Presidents",_div:"Presidents",_bye:0,_record:new _overallRecord() },
    { _ico:"i(222)",_team:"Geneva College",_conf:"Presidents",_div:"Presidents",_bye:0,_record:new _overallRecord() },
    { _ico:"i(223)",_team:"Waynesburg",_conf:"Presidents",_div:"Presidents",_bye:0,_record:new _overallRecord() },
    { _ico:"i(224)",_team:"Thiel College",_conf:"Presidents",_div:"Presidents",_bye:0,_record:new _overallRecord() },
    { _ico:"i(225)",_team:"Bethany (WV)",_conf:"Presidents",_div:"Presidents",_bye:0,_record:new _overallRecord() },
    { _ico:"i(226)",_team:"Grove City College",_conf:"Presidents",_div:"Presidents",_bye:0,_record:new _overallRecord() },
    { _ico:"i(227)",_team:"Claremont",_conf:"So. Cal.",_div:"So. Cal.",_bye:0,_record:new _overallRecord() },
    { _ico:"i(228)",_team:"Pomona-Pitzer",_conf:"So. Cal.",_div:"So. Cal.",_bye:0,_record:new _overallRecord() },
    { _ico:"i(229)",_team:"Redlands",_conf:"So. Cal.",_div:"So. Cal.",_bye:0,_record:new _overallRecord() },
    { _ico:"i(230)",_team:"Chapman",_conf:"So. Cal.",_div:"So. Cal.",_bye:0,_record:new _overallRecord() },
    { _ico:"i(231)",_team:"Cal Lutheran",_conf:"So. Cal.",_div:"So. Cal.",_bye:0,_record:new _overallRecord() },
    { _ico:"i(232)",_team:"La Verne",_conf:"So. Cal.",_div:"So. Cal.",_bye:0,_record:new _overallRecord() },
    { _ico:"i(233)",_team:"Occidental",_conf:"So. Cal.",_div:"So. Cal.",_bye:0,_record:new _overallRecord() },
    { _ico:"i(234)",_team:"Whittier",_conf:"So. Cal.",_div:"So. Cal.",_bye:0,_record:new _overallRecord() },
    { _ico:"i(235)",_team:"Hendrix College",_conf:"Southern Athletic Association",_div:"Southern Athletic Association",_bye:0,_record:new _overallRecord() },
    { _ico:"i(236)",_team:"Centre",_conf:"Southern Athletic Association",_div:"Southern Athletic Association",_bye:0,_record:new _overallRecord() },
    { _ico:"i(237)",_team:"Berry College",_conf:"Southern Athletic Association",_div:"Southern Athletic Association",_bye:0,_record:new _overallRecord() },
    { _ico:"i(238)",_team:"Washington (MO)",_conf:"Southern Athletic Association",_div:"Southern Athletic Association",_bye:0,_record:new _overallRecord() },
    { _ico:"i(239)",_team:"Chicago",_conf:"Southern Athletic Association",_div:"Southern Athletic Association",_bye:0,_record:new _overallRecord() },
    { _ico:"i(240)",_team:"Rhodes",_conf:"Southern Athletic Association",_div:"Southern Athletic Association",_bye:0,_record:new _overallRecord() },
    { _ico:"i(241)",_team:"Birmingham-Southern",_conf:"Southern Athletic Association",_div:"Southern Athletic Association",_bye:0,_record:new _overallRecord() },
    { _ico:"i(242)",_team:"Millsaps",_conf:"Southern Athletic Association",_div:"Southern Athletic Association",_bye:0,_record:new _overallRecord() },
    { _ico:"i(243)",_team:"Sewanee Univ. of the South",_conf:"Southern Athletic Association",_div:"Southern Athletic Association",_bye:0,_record:new _overallRecord() },
    { _ico:"i(244)",_team:"Southwestern University",_conf:"Southern Collegiate Athletic Conference",_div:"Southern Collegiate Athletic Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(245)",_team:"Texas Lutheran",_conf:"Southern Collegiate Athletic Conference",_div:"Southern Collegiate Athletic Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(246)",_team:"Austin College",_conf:"Southern Collegiate Athletic Conference",_div:"Southern Collegiate Athletic Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(247)",_team:"Trinity (TX)",_conf:"Southern Collegiate Athletic Conference",_div:"Southern Collegiate Athletic Conference",_bye:0,_record:new _overallRecord() },
    { _ico:"i(248)",_team:"Maryville TN",_conf:"USA South",_div:"USA South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(249)",_team:"Averett",_conf:"USA South",_div:"USA South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(250)",_team:"Huntingdon",_conf:"USA South",_div:"USA South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(251)",_team:"Ferrum",_conf:"USA South",_div:"USA South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(252)",_team:"LaGrange College",_conf:"USA South",_div:"USA South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(253)",_team:"NC Wesleyan",_conf:"USA South",_div:"USA South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(254)",_team:"Methodist",_conf:"USA South",_div:"USA South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(255)",_team:"Greensboro",_conf:"USA South",_div:"USA South",_bye:0,_record:new _overallRecord() },
    { _ico:"i(256)",_team:"St. Scholastica",_conf:"Upper Midwest",_div:"Upper Midwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(257)",_team:"Eureka College",_conf:"Upper Midwest",_div:"Upper Midwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(258)",_team:"Northwestern (MN)",_conf:"Upper Midwest",_div:"Upper Midwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(259)",_team:"MacMurray College",_conf:"Upper Midwest",_div:"Upper Midwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(260)",_team:"Minnesota-Morris",_conf:"Upper Midwest",_div:"Upper Midwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(261)",_team:"Westminster",_conf:"Upper Midwest",_div:"Upper Midwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(262)",_team:"Iowa Wesleyan",_conf:"Upper Midwest",_div:"Upper Midwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(263)",_team:"Greenville",_conf:"Upper Midwest",_div:"Upper Midwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(264)",_team:"Crown College",_conf:"Upper Midwest",_div:"Upper Midwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(265)",_team:"Martin Luther College",_conf:"Upper Midwest",_div:"Upper Midwest",_bye:0,_record:new _overallRecord() },
    { _ico:"i(266)",_team:"Wisconsin-La Crosse",_conf:"Wisconsin",_div:"Wisconsin",_bye:0,_record:new _overallRecord() },
    { _ico:"i(267)",_team:"UW-Whitewater",_conf:"Wisconsin",_div:"Wisconsin",_bye:0,_record:new _overallRecord() },
    { _ico:"i(268)",_team:"Wisconsin-Platteville",_conf:"Wisconsin",_div:"Wisconsin",_bye:0,_record:new _overallRecord() },
    { _ico:"i(269)",_team:"UW-Oshkosh",_conf:"Wisconsin",_div:"Wisconsin",_bye:0,_record:new _overallRecord() },
    { _ico:"i(270)",_team:"Wisconsin-Stevens Point",_conf:"Wisconsin",_div:"Wisconsin",_bye:0,_record:new _overallRecord() },
    { _ico:"i(271)",_team:"UW-River Falls",_conf:"Wisconsin",_div:"Wisconsin",_bye:0,_record:new _overallRecord() },
    { _ico:"i(272)",_team:"UW-Stout",_conf:"Wisconsin",_div:"Wisconsin",_bye:0,_record:new _overallRecord() },
    { _ico:"i(273)",_team:"Wisconsin-Eau Claire",_conf:"Wisconsin",_div:"Wisconsin",_bye:0,_record:new _overallRecord() },
  ],

]

var g_LEAGUE_SETTINGS = [
  { // NFL
    TEAMS:{
      GAMES_PER_WEEK:1,
      GAMES_PER_SEASON:16,
      SLOTS:["QB","WR","RB","TE","FLEX","D/ST","K"],
      MAX_SLOTS:{ QB:1,WR:2,RB:2,TE:1,FLEX:1,"D/ST":1,K:1 },
      MAX_META_SLOTS:{ QB:0,WR:1,RB:1,TE:1,FLEX:0,"D/ST":0,K:0 },
      MAX_SLOT_START_AVG:{ QB:26,WR:30,RB:30,TE:20,FLEX:30,"D/ST":16,K:20 },
      LEAGUE_BUFFER:{ QB:10,WR:40,RB:40,TE:20,FLEX:0,"D/ST":10,K:10 },
      MAX_SHOW_TEAM_SLOTS:{ QB:2,WR:4,RB:4,TE:2,FLEX:2,"D/ST":2,K:2 },
    },
    LEAGUE:{
      TOTAL_SHOW_TEAMS: 32,
      MAX_CONFERENCES:2,  // 32 teams
      MAX_DIVISIONS:4,
      MAX_TEAMS_PER_DIVISION:4,
      MAX_LEAGUES:1,
    },
    ICONS:"IMG/NFL/81x54/",
  },
  { // DIV I
    TEAMS:{
      GAMES_PER_WEEK:1,
      GAMES_PER_SEASON:13,
      SLOTS:["QB","WR","RB","TE","FLEX","D/ST","K"],
      MAX_SLOTS:{ QB:1,WR:2,RB:2,TE:1,FLEX:1,"D/ST":1,K:1 },
      MAX_META_SLOTS:{ QB:0,WR:1,RB:1,TE:1,FLEX:0,"D/ST":0,K:0 },
      MAX_SLOT_START_AVG:{ QB:26,WR:30,RB:30,TE:20,FLEX:30,"D/ST":16,K:20 },
      LEAGUE_BUFFER:{ QB:10,WR:40,RB:40,TE:20,FLEX:0,"D/ST":10,K:10 },
      MAX_SHOW_TEAM_SLOTS:{ QB:2,WR:4,RB:4,TE:2,FLEX:2,"D/ST":2,K:2 },
    },
    LEAGUE:{
      TOTAL_SHOW_TEAMS: 128,
      MAX_CONFERENCES:2,  // 128 teams
      MAX_DIVISIONS:4,
      MAX_TEAMS_PER_DIVISION:5,
      MAX_LEAGUES:1,
    },
    ICONS:"IMG/NCAA/I/",
  },
  { // DIV I AA
    TEAMS:{
      GAMES_PER_WEEK:1,
      GAMES_PER_SEASON:12,
      SLOTS:["QB","WR","RB","TE","FLEX","D/ST","K"],
      MAX_SLOTS:{ QB:1,WR:2,RB:2,TE:1,FLEX:1,"D/ST":1,K:1 },
      MAX_META_SLOTS:{ QB:0,WR:1,RB:1,TE:1,FLEX:0,"D/ST":0,K:0 },
      MAX_SLOT_START_AVG:{ QB:26,WR:30,RB:30,TE:20,FLEX:30,"D/ST":16,K:20 },
      LEAGUE_BUFFER:{ QB:10,WR:40,RB:40,TE:20,FLEX:0,"D/ST":10,K:10 },
      MAX_SHOW_TEAM_SLOTS:{ QB:2,WR:4,RB:4,TE:2,FLEX:2,"D/ST":2,K:2 },
    },
    LEAGUE:{
      TOTAL_SHOW_TEAMS: 125,
      MAX_CONFERENCES:2,  // 125 teams
      MAX_DIVISIONS:4,
      MAX_TEAMS_PER_DIVISION:5,
      MAX_LEAGUES:1,
    },
    ICONS:"IMG/NCAA/I-AA/",
  },
  { // DIV II
    TEAMS:{
      GAMES_PER_WEEK:1,
      GAMES_PER_SEASON:12,
      SLOTS:["QB","WR","RB","TE","FLEX","D/ST","K"],
      MAX_SLOTS:{ QB:1,WR:2,RB:2,TE:1,FLEX:1,"D/ST":1,K:1 },
      MAX_META_SLOTS:{ QB:0,WR:1,RB:1,TE:1,FLEX:0,"D/ST":0,K:0 },
      MAX_SLOT_START_AVG:{ QB:26,WR:30,RB:30,TE:20,FLEX:30,"D/ST":16,K:20 },
      LEAGUE_BUFFER:{ QB:10,WR:40,RB:40,TE:20,FLEX:0,"D/ST":10,K:10 },
      MAX_SHOW_TEAM_SLOTS:{ QB:2,WR:4,RB:4,TE:2,FLEX:2,"D/ST":2,K:2 },
    },
    LEAGUE:{
      TOTAL_SHOW_TEAMS: 170,
      MAX_CONFERENCES:2,  // 170 teams
      MAX_DIVISIONS:4,
      MAX_TEAMS_PER_DIVISION:5,
      MAX_LEAGUES:1,
    },
    ICONS:"IMG/NCAA/II/",
  },
  { // DIV III
    TEAMS:{
      GAMES_PER_WEEK:1,
      GAMES_PER_SEASON:12,
      SLOTS:["QB","WR","RB","TE","FLEX","D/ST","K"],
      MAX_SLOTS:{ QB:1,WR:2,RB:2,TE:1,FLEX:1,"D/ST":1,K:1 },
      MAX_META_SLOTS:{ QB:0,WR:1,RB:1,TE:1,FLEX:0,"D/ST":0,K:0 },
      MAX_SLOT_START_AVG:{ QB:26,WR:30,RB:30,TE:20,FLEX:30,"D/ST":16,K:20 },
      LEAGUE_BUFFER:{ QB:10,WR:40,RB:40,TE:20,FLEX:0,"D/ST":10,K:10 },
      MAX_SHOW_TEAM_SLOTS:{ QB:2,WR:4,RB:4,TE:2,FLEX:2,"D/ST":2,K:2 },
    },
    LEAGUE:{
      TOTAL_SHOW_TEAMS: 250,
      MAX_CONFERENCES:2,  // 250 teams
      MAX_DIVISIONS:4,
      MAX_TEAMS_PER_DIVISION:5,
      MAX_LEAGUES:1,
    },
    ICONS:"IMG/NCAA/III/",
  },
]